---
title: "Stats 506, Statistical Computing"
author: "Instructor: James Henderson, PhD"
date: "Fall 2017"
output: 
  html_document:
    theme: journal
    highlight: pygments
    css: styles.css
---

<div style = "text-align: center; margin-left: 20%; margin-right: 20%; 
  background-color: beige">

## Course Materials 
  <div style = "text-align: left; margin-left: 10%; margin-right: 10%">
  <a href="./Syllabus.html">Syllabus</a>

  <a href="./Course_Overview.html">Course Overview</a>
  
  <a href="./Git.html">Version control using Git</a>
  
  <a href="./LinuxShellSkills.html">Linux Shell Skills</a>
  
  <a href="./Short_Introduction_to_Stata.html">A Short Introducton to Stata</a>

  <a href="./ProblemSet1.html">Problem set 1</a> [<a href="./StyleRubric.html">Style rubric</a>]

  <a href="./Language_Comparisons.html">Common Commands (in R and Stata)</a>

  <a href="./Introduction_to_R.html">An Introducton to R</a>

  <a href="./dplyr.html">RECS Case Study: Home Types</a>
  
  <a href="./MonteCarloSimulation.html">Monte Carlo Simulation and Vectorization in R</a>
  
  <a href="./StringManipulation.html">String Manipulation and Regular Expressions</a>
  
  <a href="./ComputationalMethods.html">Bootstrapping and Permutation Tests</a>
  
  <a href="./ProblemSet2.html">Problem Set 2</a> [[Solutions](./PS2_solutions.zip)]
  
  <a href="./Parallel_Computing_R.html">Parallel Computing in R</a>

  <a href="./OOP_R.html">Object Oriented Programming in R</a>

  <a href="./GLM_Methods.html">S3 in action: GLM Methods</a>

  <a href="./MatrixDecompositions.html">Matrix Decompositions</a>

  [Midterm](./midterm_506_F17.pdf) [[Corrections (Take Home)](./Midterm_Corrections.pdf)] [[Solutions](./Midterm_solutions.pdf)]
  
  [Batch Computing and Job Scheduling](./BatchComputing.html)
  
  [Problem Set 3](./ProblemSet3.html), [Solutions](PS3_Solutions.html)
  
  [R’s data.table package](./data.table.html)
  
  [Course Project](./CourseProject.html)
  
  [Basic SQL](./Intro_to_SQL.html)

  [Basic SAS](./Basic_SAS.html)

  [Problem Set 4](./ProblemSet4.html)

  [Memory in R](./MemoryProfiling.html)

  [Using C/C++ from R](./Using_C_Cpp.html)

  [Distributed Computing](./DistributedComputing.html)
  </div>
  <div>
  </div>
</div>
