---
title: "A Short Introduction to Stata"
author: 
date: 
output:
  html_document:
    theme: journal
    highlight: pygments
    css: styles.css
---

## About Stata

[Stata](https://en.wikipedia.org/wiki/Stata) is a statitical software package
most frequently used for data analysis in academic research. It is especially popular in
health services research, epidemiology, and various social sciences.  

Two commands that make Stata particularly appealing in these fields are:

  + [margins](https://www3.nd.edu/~rwilliam/stats/Margins01.pdf) for post-estimation
    summaries such as adjusted predictions and marginal effects,

  + [svy](https://www.stata.com/manuals13/svy.pdf)
  for incorporating survey weights into an analysis.
  
### Licensing
Stata is commercial software that requires a license is required for use. As a UM
student you can use Stata on the SCS servers by typing `stata` at the command line.
There are a limited number of licenses available, so please do not leave Stata open
when not in use.  Also be aware that all the licenses could be in use at busy times,
such as the night before an assignment for this course is due.

### Markdown
Stata does support [markdown](https://www.stata.com/new-in-stata/markdown/) from version 15, but the most recent version of Stata on the SCS servers is 15:

```bash
which stata
ls /usr/local/bin/ | grep "stata"   
```

### One Data, Two Types

Stata primarily works with a single rectangular data set with
observations in rows and variables in columns.  Variables can
be referred to by name.

Stata variables come in two primary *types* - *numeric* and *string*.
Strings are stored using as `str#` with `#` indicating the maximum length.

Numeric variables come in the following storage types:

Storage Type | Bytes | What
-------------|-------|-----
byte | 1 | small integers (up to $2^8- 1=256$)
int | 2 | big integers (up to $2^16-1$)
long | 4 | very big integers
float | 4 | up to 38 decimal places
double | 8 | up to 323 decimal place
____________________________________

Stata programs generally prefer / require numeric types.

Running `compress` instructs Stata to switch variables to smaller storage types
where possible.

## Using Stata

### Command Syntax

A common pattern for commands in Stata is,

```stata
/* Template */
command <variable(s)>, <option>

/* Example */
command regress A1C BMI, level(99)
```

where `command` is the name of command followed, when needed,
by one or more specific variables (columns) to operate on, and then a list of
options for modifying default behavior.  If you are familiar with functions in 
languages like `R` or `python` that follow a syntax `f(var1,var2)`
you can think of commands as rough equivalents with variables being necessary
arguments and options being, well, *optional* arguments. 

The syntax for specific commands may vary from this pattern and it is a good idea
to read the help documentation when using a command for the first time:

```stata
/* Template */
help <command> 

/* Example */
help regress
```

### Basic commands

  + `use`, `sysuse`, `webuse` - load a Stata native `.dta` file into memory
  + `import delimited` - read delimted data files
  + `clear` - clear the current data
  + `save`
  + `help`
  + `describe` - overview of the current data set
  + `list` - list a subset of variables; useful with i.e. `list <var> in 1/10`
  + `summarize` - compute and display summary statistics
  + `codebook` - summarize entire dataset
  + `tabulate` - compute frequency tables
  + `exit` - quit Stata

### Stata scripts or `.do` files

A *script* is a set of instructions to a computing language 
for carrying out a particular purpose such as data preperation or
analysis. Stata scripts use the extension `.do` and will generally be your
primary way of interacting with and using Stata.

You can execute a do file by typing, i.e. `stata -b my_analysis.do` at the
command line or `do my_analysis` within an interactive Stata console.

Scripts serve several purposes:

  1. Serve as a record for how a particular analysis was carried out,
  
  2. Communicate to others (including future you `r emo::ji("confused")`) your thought
     process during an analysis,
  
  3. Communicate a set of instructions for what you want Stata *to do*.

When learning a new computing language it is not uncommon to get hung up on item 3, 
aka *syntax*, at the expense of other purposes a script serves. You can combat 
this tendency by paying attention to *style* and developing good commenting habits.

Here are some opinions on style in Stata: 

  + [Style is the Essential](https://michaelshill.net/2015/07/31/in-stata-coding-style-is-the-essential/)

  + [Suggestions on Stata Programming Style](http://www.stata-journal.com/sjpdf.html?articlenum=pr0018)


### Data Management

The following commands are useful for manipulating data in Stata:

 + `keep`, `drop` - keep or drop a subset of variables
 + `generate` - create a new variable using functions of existing ones
 + `replace` - replace an existing variable, especially useful with `replace <var> if <condition>`
 + `label` - change display labels for variables
 
   - `label variable`
   - `label define`
   - `label values`
   - `label data`

 + `encode`, `decode` - use to switch between string and integer representation for categorical variables
 + `recode` - to recode into different values, i.e $0 \to 1, 1 \to 0$

The data mangagement demonstration from class can be found at: 
[RECS_prep_subset1.do](https://raw.githubusercontent.com/jbhender/Stats506/master/Stata/RECS/RECS_prep_subset1.do).

#### Boolean Operators

Boolean operators are useful for generating values conditionally on other values.
Here are the basics:

 Operator | Meaning 
-----------|-------
 & | and
 \| | or
== | equal
!= | not equal
>, >= | greater than (or equal to)
<, <= | less than (or equal to)

### Regression

We will review the regression example from
[Professor Shedden's Stata Intro](http://dept.stat.lsa.umich.edu/~kshedden/Courses/Stat506/stata_intro/).

The key Stata commands in the demonstration are:

  + `regress <dv> <ivlist>, options` - for computing regression
  + `display` - for evaluating an expression
  + `r()` and `e()` - for extracting results from the most recent command
  + `c.`, `i.` - for instructing Stata how to treat variables
  + `#`, `##` - for specifying interaction terms

The script from the in-class demonstration can be found at:
[RECS_survey](https://github.com/jbhender/Stats506/blob/master/Stata/RECS/RECS_Consump_Analysis.do)

Some important data analysis principals:

 + Pay attention to the scale of your variables
 + Summarize on a natural easy to understand scale
 + Center variables before creating interactions to reduce collinearity.

### Macros & Programming Statements

In Stata "variable" always refer to a column of the dataset.  However, in programming
it is also useful to have access to variables of differing dimensions.  

"Macros" serve this role in Stata and are somewhat similar to shell variables in 
bash and other Linux shells.  A macro is a string that is interspersed into a
Stata program and evaluated when that program is executed.  The key to understanding 
and using Stata macros is knowing when they are evaluated.

A local macro can be defined by:

```stata
local life_questions 42
```

The value of a macro is retrieved by encapuslation between a backtick "`" and 
an apostrophe "'":

```stata
display `life_questions'
```
Macros are frequently used in loops:

```stata
foreach var in varlist yearmade-kwh {
  summarize `var'
}
```

Examples of Stata loops can be found in the data managment script linked above
and the data merge example here: 
[RECS_merge.do](https://raw.githubusercontent.com/jbhender/Stats506/master/Stata/RECS/RECS_merge.do).


## Extending Stata

Many Stata commands are defined by [.ado](https://www.stata.com/manuals/u17.pdf)
 files rather than built into the Stata
source code.  Some of these commands are user-contributed and you can extend
the functionality of Stata by obtaining programs written as `.ado` files or writing your own.

Those interested can learn more about programming Stata [here](https://www.stata.com/manuals/u18.pdf).

**Disclaimer**: You will *not* need to know anything about `.ado` files for problem sets
or exams in this course.


## Resources

You may find the following resources useful in learning to use Stata:

  + [Stata documenation](https://www.stata.com/features/documentation/)


These notes are based in large part on:

  + [Professor Shedden's Stata Intro](http://dept.stat.lsa.umich.edu/~kshedden/Courses/Stat506/stata_intro/)

  + [Dr. Errickson's CSCAR Workshop Notes](https://github.com/josherrickson/workshop-stata-intro-book/tree/master/stata_markdown)
