---
title: "<a href='./index.html'>Statistics 506, Fall 2018</a>"
author: Computational Methods and Tools in Statistics
date: 
output: 
  html_document:
    theme: journal
    highlight: pygments
    include:
      after_body: ../footer.html
    css: ../styles.css
---

# Syllabus

## Contact Information:

  + Instructor: James Henderson (jbhender@umich.edu)
  + Instructor office: 3530-A Rackham 
  + Instructor office hours: 11-12:30 Wednesday, 1:00-2:30 Thursday
  + GSI: Roger Fan (rogerfan@umich.edu)
  + GSI office hours: TBD, 1720 Chemistry

## Key Dates:
  + Drop/Add deadline: Sep 24
  + In-class midterm exam: Tu Oct 23
  + Projects due: TBD
  + Final Exam: M, December 17 1:30-3:30
  + No Class: Tu Oct 16 (Study Break), Th Nov 22 (Holiday)
  + <a href="http://ro.umich.edu/">Office of the Registrar</a>

If exam or project due dates interfere with religious holidays you observe 
please let me know as soon as possible so we may work out alternative arrangements.
  
## Grading information:
  + Midterm exam: 15%
  + Final exam: 20%
  + Course projects (2): 20% (10% each) 
  + Homework (~4 sets): 40%
  + Readings & Quizzes: 5% 
 
## Text books
There are no required texts for this course. There are three recommend texts.

*The Art of R Programming*, by Norman Matloff, is recommended for those 
with little to no previous experience in R.

[Advanced R](https://adv-r.hadley.nz/), by Hadley Wickham, is recommended for those 
who would like to develop a deep understanding of R and its inner workings.

[R for Data Science](http://r4ds.had.co.nz/), by Garrett Grolemund and
Hadley Wickham, is a helpful bridge between these two. 

## Pre-requisites: 

You should have taken or be currently enrolled in an 
intermediate applied statistics course such as 
Stats 500, and you should be comfortable programming in at least one 
programming language or scripting in a statistical software language.

## Course Description: 
Statistics 506 covers a variety of topics related to the use of computing for analyzing,
managing, and presenting data. We will cover the topics below along with several case studies:

  + Overview of computing languages for statistical computing
  + General computing:
    - Linux shell and utilities
    - Version control with git
    - Literate programming
    - Testing, verifying, and profiling code
  + Basic computer architecture and networking
  + Basic Stata
  + Basic SAS
  + Basic and advanced R:
    - R basics
    - Rmarkdown
    - Vectorization, functions
    - dplyr, data.tables, and other tools for split/apply/combine in R
    - Rcpp, using C/C++ within R
    - parallel programming in R
  + SQL
  + Batch computing and job scheduling (PBS)

## Computing Resources

All of the software in this course is available without charge for UM students.
Some software, such as R, is free and open source and can be installed on your
personal machine. You should install both R and RStudio as described in steps
1 and 2 <a href="https://jbhender.github.io/R_Workshop_Prep.html">here</a>. 

You will also need an ssh client, such as Terminal (Mac), 
[Putty](https://www.putty.org/) (Windows) or [Powershell](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/getting-started-with-windows-powershell?view=powershell-6) (Windows).

## Submitting work late

You are expected to turn in all work by the due dates listed on canvas. However,
to accommodate unexpected circumstances you may utilize up to ten "late days" for 
submitting homework or quizzes subject to the following restrictions.  Each
late day utilized grants you a 24-hour extension to submit the assignment. Late
days may only be utilized in integer increments. There is a maximum of 1 late day
for any single quiz. Late days can not be used for projects or exams. 

## Accomodations for students with disabilities

If you think you need an accommodation for a disability, please let me know at your earliest convenience. Some aspects of this course, 
the assignments, the in-class activities, and the way the course is usually taught may be modified to facilitate your participation and progress. 
As soon as you make me aware of your needs, we can work with the Services for Students with Disabilities (SSD) office to help us determine appropriate 
academic accommodations. 
SSD (734-763-3000; http://ssd.umich.edu)
 typically recommends accommodations through a Verified Individualized Services and Accommodations (VISA) form. 
Any information you provide is private and confidential and will be treated as such.

## Academic Integrity
Unless specifically stated otherwise, students are expected to complete homework and other assignments independently without copying code or text from other students in this course. Students are encouraged to discuss problem sets and to help one another with concepts and syntax, but such discussions should not reach the point of representing one student’s work as another’s.

Use of materials from other sources should fall within the license for those materials and include proper attribution.

For more on academic integrity, please be advised of Rackham policy: http://www.rackham.umich.edu/policies/academic-policies/section11.


## Mandatory Reporting and Sexual Misconduct

Title IX prohibits sex discrimination to include sexual misconduct: harassment, domestic and dating violence, sexual assault, and stalking. If you or someone you know has been harassed or assaulted, you can receive confidential support and academic advocacy at the Sexual Assault Prevention and Awareness Center (SAPAC). SAPAC can be contacted on their 24-hour crisis line, 734-936-3333 and online at sapac.umich.edu. Alleged violations can be reported non-confidentially to the Office for Institutional Equity (OIE) at institutional.equity@umich.edu. Reports to law enforcement can be made to University of Michigan Police Department at 734-763-3434.

As an instructor, one of my responsibilities is to help create a safe learning environment on our campus. I also have a mandatory reporting responsibility. I am required to share information regarding sexual misconduct or information about a crime that may have occurred on U-M's campus with the University. Students may speak to someone confidentially by contacting SAPAC’s Crisis Line at (734) 936-3333.

